---
title: "Kobe Shot Predictor"
author: "Daniel Byrne"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(car)
library(relaimpo)
library(bootstrap)
layout(matrix(c(1,2,3,4),2,2))
library(aod)
library(ggplot2)
library(fmsb)
```


```{r}
# read data
kobe = read.csv("./project2Data.csv")

# set factors
kobe$action_type = factor(kobeshotdata$action_type)
kobe$shot_type = factor(kobeshotdata$shot_type)
kobe$combined_shot_type = factor(kobeshotdata$combined_shot_type)
kobe$shot_zone_area = factor(kobe$shot_zone_area)
kobe$shot_zone_basic = factor(kobe$shot_zone_basic)
kobe$shot_zone_range = factor(kobe$shot_zone_range)
kobe$season = factor(kobe$season)
kobe$playoffs = factor(kobe$playoffs)
kobe$shot_made_flag = factor(kobe$shot_made_flag)
kobe$period = factor(kobe$period)
```

## 2 pt shot models
```{r}
## Filter to only 2 pt shots
kobe2pts = kobe %>% filter(shot_type == "2PT Field Goal" & shot_zone_area != "Back Court(BC)" & !shot_zone_basic %in% c("Right Corner 3","Left Corner 3","Above the Break 3"))
summary(kobe2pts)
```


### Shot type as a predictor
```{r}
twosTypes = glm(shot_made_flag ~ combined_shot_type, data =kobe2pts, family="binomial")
summary(twosTypes)
```

### Shot distance(y) as a predictor for 2 pt shots
```{r}
twosDist = glm(shot_made_flag ~  shot_zone_range + shot_zone_basic + loc_y, data = kobe2pts, family = "binomial" )
summary(twosDist)
```

### shot distance(x) as a predictor

```{r}
twosx = glm(shot_made_flag~ shot_zone_area + loc_x, data=kobe2pts,family="binomial")
summary(twosx)

```

## 3 points shots

```{r}

kobe3pts = kobe %>% filter(shot_type == "3PT Field Goal" & shot_zone_range  %in% c("24+ ft.","16-24 ft.") & shot_distance > 23)
summary(kobe3pts)
```

### 3pts predicted by distance(y)

```{r}
threesDist = glm(shot_made_flag ~ shot_distance, data = kobe3pts, family = "binomial" )
summary(threesDist)
```

### 3pts predicted by distance(x)

```{r}
threesDist1 = glm(shot_made_flag ~ loc_x + shot_zone_area, data = kobe3pts, family = "binomial" )
summary(threesDist1)
threesDist2 = glm(shot_made_flag ~ loc_x + shot_zone_basic, data = kobe3pts, family = "binomial" )
summary(threesDist2)
```

### 3pts by year

```{r}
threesDist1 = glm(shot_made_flag ~ season, data = kobe3pts, family = "binomial" )
summary(threesDist1)
```